<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <OutputType>Exe</OutputType>
        <UsesTUnit>true</UsesTUnit>
      <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="TUnit.Engine" />
      <PackageReference Include="TUnit.Assertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NexusMods.Sdk\NexusMods.Sdk.csproj" />
  </ItemGroup>

</Project>
