# PUPNET DEPLOY: 1.6.0

# PupNet automatically finds this file https://github.com/kuiperzone/PupNet-Deploy?tab=readme-ov-file#introduction-
# if it is in the current working directory.

# Reference Config: https://raw.githubusercontent.com/kuiperzone/PupNet-HelloWorld/main/HelloWorld.pupnet.conf

# APP PREAMBLE
AppBaseName = tModManager
AppFriendlyName = tModManager
AppId = io.github.t4toh.tmodmanager
# Fallback; dev.sh (opcion 10) lo pisa con --app-version tomado del ultimo tag git
AppVersionRelease = 0.0.1[1]
AppShortSummary = Mod manager for Cyberpunk 2077 on Linux (Steam/Proton).
AppDescription = """"""
AppLicenseId =  GPL-3.0-only
AppLicenseFile =
AppChangeFile =

# PUBLISHER
PublisherName = Tatoh
PublisherCopyright = Copyright (C) Nexus Mods 2024, Tatoh 2026
PublisherLinkName = Home Page
PublisherLinkUrl = https://github.com/T4toh/tModManager
PublisherEmail =

# DESKTOP INTEGRATION
DesktopNoDisplay = false
DesktopTerminal = false
DesktopFile = io.github.t4toh.tmodmanager.desktop
MetaFile = io.github.t4toh.tmodmanager.metainfo.xml
IconFiles = """
    icon.ico
    icon.svg
"""

# DOTNET PUBLISH
DotnetProjectPath =
DotnetPublishArgs = -p:Version=${APP_VERSION} --self-contained true -c Release -p:TieredCompilation=true -p:PublishReadyToRun=true -p:PublishSingleFile=true
DotnetPostPublish =
DotnetPostPublishOnWindows =

# PACKAGE OUTPUT
PackageName = tModManager
OutputDirectory = Deploy/OUT

# APPIMAGE OPTIONS
AppImageArgs = --no-appstream
AppImageVersionOutput = false

# WINDOWS SETUP OPTIONS
SetupAdminInstall = false
SetupCommandPrompt =
SetupMinWindowsVersion = 10
SetupSignTool =
SetupSuffixOutput =
SetupVersionOutput = false
SetupUninstallScript = "uninstall.bat"







# unused but required
FlatpakPlatformRuntime = org.freedesktop.Platform
FlatpakPlatformSdk = org.freedesktop.Sdk
FlatpakPlatformVersion = 23.08
