<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UsesXunitDI>false</UsesXunitDI>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Verify.XunitV3"/>
        <PackageReference Include="Verify.SourceGenerators"/>
        <!-- Verify.SourceGenerators needs Microsoft.CodeAnalysis >= 4.9 at runtime -->
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>

    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\NexusMods.Abstractions.Games.Diagnostics\NexusMods.Abstractions.Games.Diagnostics.csproj" />
        <ProjectReference Include="..\..\src\NexusMods.App.Generators.Diagnostics\NexusMods.App.Generators.Diagnostics.csproj" />
    </ItemGroup>

</Project>
