<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Verify.XunitV3"/>
        <PackageReference Include="Verify.SourceGenerators"/>

        <PackageReference Remove="Xunit.DependencyInjection" />
        <PackageReference Remove="Xunit.DependencyInjection.Logging" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\NexusMods.Abstractions.Games.Diagnostics\NexusMods.Abstractions.Games.Diagnostics.csproj" />
        <ProjectReference Include="..\..\src\NexusMods.App.Generators.Diagnostics\NexusMods.App.Generators.Diagnostics.csproj" />
    </ItemGroup>

</Project>
